# Generated by Django 2.0.1 on 2018-04-19 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='max_order',
            new_name='max_amount',
        ),
    ]
