# Generated by Django 2.0.1 on 2018-04-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_order_orderlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Product status: In warehouse - Out for delivery - Delivered - Cancelled', max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
