# Generated by Django 2.0.1 on 2018-04-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20180422_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='x_coordinate',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='y_coordinate',
            field=models.IntegerField(default=1),
        ),
    ]
