# Generated by Django 2.0.1 on 2018-04-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20180422_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ups_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
