# Generated by Django 2.0.1 on 2018-04-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_order_ups_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=1)),
                ('y', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='orderlist',
            name='description',
            field=models.CharField(default='Product description', max_length=2000),
        ),
    ]
