# Generated by Django 2.0.1 on 2018-04-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20180424_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_prime',
            field=models.IntegerField(default=0),
        ),
    ]
