# Generated by Django 2.0.1 on 2018-04-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_order_is_prime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ups_account',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
