# Generated by Django 2.0.1 on 2018-04-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20180426_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ups_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
