# Generated by Django 2.0.1 on 2018-04-27 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_coupon_ordertime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertime',
            name='order',
        ),
        migrations.DeleteModel(
            name='OrderTime',
        ),
    ]
