# Generated by Django 2.0.1 on 2018-04-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_warehousestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousestock',
            name='whid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
