# Generated by Django 2.0.1 on 2018-04-27 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_warehousestock_whid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='warehousestock',
            unique_together={('whid', 'product')},
        ),
    ]
